#C environment

FROM debian

RUN apt-get update && apt-get upgrade -y \
	&& apt-get install -y build-essential git

# How to build it?
# docker build -t ex00 .

# How to run it?
# docker run --rm -ti ex00
